[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python app_flask.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { }
