[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python iris_flask.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { }
